apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-yml-nginx
  labels:
    app: yml-App
spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: yml-App
  template:
    metadata:
      labels:
        app: yml-App
    spec:
      containers:
        - name: yml-nginx-cont
          image: shubhsamaksha/jenkins_project:my_tomcat9_image
          ports: 
            - containerPort: 80
