apiVersion: api/v1
kind: Deployment
metadata:
  name: test-yml-nginx
  labels:
    app: yml-App
Spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: yml-App
templates:
  metadata:   
    app: yml-App
Spec:
  Containers:
    - name: yml-nginx-cont
      image: shubhsamaksha/v02:latest
      ports: 
      - Containerport: 80          
